curso_index:
    path:     /
    defaults: { _controller: "AppBundle:Curso:index" }
    methods:  GET

curso_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Curso:show" }
    methods:  GET

curso_new:
    path:     /new
    defaults: { _controller: "AppBundle:Curso:new" }
    methods:  [GET, POST]

curso_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Curso:edit" }
    methods:  [GET, POST]

curso_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Curso:delete" }
    methods:  DELETE
